modLoader = "javafml"
loaderVersion = "[${forge_major},)"
license = "MIT"
issueTrackerURL = "https://github.com/teamCreating/MTR-Map-Overlay/issues"

[[mods]]
modId = "mtrmap"
version = "${version}"
displayName = "MTR Map Overlay"
description = '''Displays MTR route ribbons, track geometry and map-only station/platform icons on Xaero's World Map and JourneyMap. Supports optional full-network sync when installed on the server.'''
logoFile = "assets/mtrmap/icon.png"
authors = "BenLi06"

[[dependencies.mtrmap]]
modId = "forge"
mandatory = true
versionRange = "[${forge_major},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtrmap]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtrmap]]
modId = "mtr"
mandatory = true
versionRange = "[${mtr_version},4.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtrmap]]
modId = "xaerominimap"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.mtrmap]]
modId = "xaeroworldmap"
mandatory = false
versionRange = "[1.45.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.mtrmap]]
modId = "journeymap"
mandatory = false
versionRange = "[${journeymap_minimum},)"
ordering = "AFTER"
side = "CLIENT"

